### Create Job
POST http://localhost:8000/api/jobs
Content-Type: application/json

{
  "company": "DemoCo",
  "city": "Almaty",
  "min_experience": 2,
  "title": "Frontend Developer",
  "education": "Bachelor",
  "languages": "ru,en",
  "salary_min": 400000,
  "salary_max": 800000,
  "employment_type": "full-time",
  "description": "React + TS"
}

### Create Candidate
POST http://localhost:8000/api/candidates
Content-Type: application/json

{
  "name": "Aruzhan",
  "email": "aru@example.com",
  "city": "Almaty",
  "years_experience": 2,
  "title": "Frontend Developer",
  "education": "Bachelor",
  "languages": "ru,en",
  "salary_expectation": 500000,
  "employment_type": "full-time",
  "resume_text": "React projects with metrics",
  "source": "manual"
}

### Match
POST http://localhost:8000/api/match/1/1
